[package]
name = "iced_lens"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
fluent-bundle = "0.16.0"
fluent-syntax = "0.12.0"
iced = { version = "0.12", features = ["tokio", "svg", "image"] }
image = "0.25.9"
pico-args = "0.5.0"
resvg = "0.45.1"
rust-embed = "8.9.0"
serde = { version = "1.0.228", features = ["derive"] }
sys-locale = "0.3.2"
tiny-skia = "0.11.4"
toml = "0.9.8"
unic-langid = "0.9.6"
